FROM ubuntu
RUN apt-get update && \
    apt-get install -y supervisor python3-pip python3-dev libmysqlclient-dev mysql-client

WORKDIR /worker
COPY . .
RUN pip3 install -r requirements.txt

COPY ./worker/supervisord.conf /etc/supervisor/supervisord.conf
COPY ./worker/celery_worker.conf /etc/supervisor/conf.d/celery_worker.conf
COPY ./worker/entrypoint.sh /worker

ENTRYPOINT ["sh", "entrypoint.sh"]